### ISSUE TITLE
怎么在现在的系统里实现sso登录用于集成之前存在的用户系统呢？

### ISSUE THREAD

**Issue by devqin** [kaiyuanshe/open-hackathon#651]
rt.
我之前有个网站，有一些用户数据，现在想要在这个open-hackthon系统中实现一个sso登录的需求，可以方便的从之前存在的用户系统获得用户数据，该怎么做最好呢？

**Comment by juniwang** [comment]
open-hackathon登录使用标准的oauth，只要你的网站支持oauth即可
