### ISSUE TITLE
无法下载azure证书

### ISSUE THREAD

**Issue by handsome-feng** [kaiyuanshe/open-hackathon#657]
你好，我在发布活动的时候，创建Azure证书后，浏览器没有自动下载证书文件，且我在“Azure证书列表”那里手动点击下载，出现的路径是“http://localhost:15000/static/upload/azure_cert/20180831/68332c6f-5702-4003-ad4a-xxxxxxxxxx.cer”, 无法下载，请问怎么处理？

**Comment by juniwang** [comment]
Azure暂不支持
