### ISSUE TITLE
The guacamole-server link in develop guide seems wrong

### ISSUE THREAD

**Issue by chensong2000** [kaiyuanshe/open-hackathon#659]
I tried to download guacamole-server-0.9.9.tar.gz with the link "http://guac-dev.org/release/release-notes-0-9-9" in developr_guide.md, i got 404.

**Comment by chensong2000** [comment]
http://guacamole.apache.org/releases/0.9.9/ seems right

**Comment by juniwang** [comment]
actually we need to use a much newer version of Guacamole. The documented version was release 2 years ago:)

**Comment by chensong2000** [comment]
obsolete
