### ISSUE TITLE
SPIKE on kubernetes integration

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/open-hackathon#663]
- Install python libraries for Kubernetes, a.k.a K8S
- KUBECONFIG file management(in a secure way)
- possible K8S spec management
- Setup test K8S cluster, better Huawei Cloud
- Select a Docker registry: Docker hub or its alternative such as Azure Container Registry. Docker Hub is usually blocked in China. It's possible that we must support multiple docker registries because we need to support K8S on multiple cloud providers

**Comment by chensong2000** [comment]
which k8s client module we work with:
pip install kubernetes(https://github.com/kubernetes-client/python) ?

**Comment by juniwang** [comment]
Yes, the official one is active and of the most quality
