### ISSUE TITLE
azure hosted docker 逻辑清理

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/open-hackathon#711]
- 后台大部分逻辑可以删除，暂留alauda相关即可，注意接口验证部分，需要禁止azure hosted docker。
- 前端创建活动和管理界面删除azure 相关入口。 Azure 证书相关界面一并删除

**Comment by chensong2000** [comment]
cleaned azure in the backend, pr is in review. (https://github.com/kaiyuanshe/open-hackathon/pull/738)
need help form frontend

**Comment by chensong2000** [comment]
backend is done: https://github.com/kaiyuanshe/open-hackathon/pull/738
frontend needs help

**Comment by chensong2000** [comment]
done e2d162995fc4b55ea96b21e4c3cb0c8388cdc25f
