### ISSUE TITLE
项目容器化

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/open-hackathon#715]
- 整个hackathon平台docker化，所有组建变成容器. 需要提供全部的Dockerfile。容器放到docker hub或者华为云均可。
- 最好提供k8s使用的yaml文件，可意见部署hackathon
- 数据库必须使用persist volume, 最好能方便备份

**Comment by Coderhypo** [comment]
pv 可以调研下是否能利用平台的能力，比如 awsElasticBlockStore，Azure Disk，不知道华为云有没有可以支持 k8s 的存储

**Comment by chensong2000** [comment]
https://github.com/kaiyuanshe/open-hackathon/pull/729

**Comment by chensong2000** [comment]
https://github.com/kaiyuanshe/open-hackathon/pull/730
