### ISSUE TITLE
K8SStarter优化 - 需要支持模版

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/open-hackathon#724]
此任务太大，可能需要进一步拆分。

目前的模版是配置在config.py里面的，无法同时支持多个活动，也非常不灵活。需要修改原模版管理功能：
- 界面删除原docker相关界面，改为k8s相关参数。或者提供yaml文件上传入口
- 需要恢复原模版测试功能。能成功启动的模版需要修改状态为已验证
- 模版有可能需要placeholder，需要仔细设计
- 由于不同的云厂商可能有不同的配置，需要从架构的角度考虑支持这种差异性
- 模版文件的保存需要仔细考虑，可能会用敏感信息(可能需要扩展现有Storage的实现)。

**Comment by Coderhypo** [comment]
对于模板我比较疑惑的是现在逻辑是远程加载，能不能考虑把模板内容放在数据库里
