### ISSUE TITLE
decouple config files from source code

### ISSUE THREAD

**Issue by chensong2000** [kaiyuanshe/open-hackathon#736]
currently, all the configurations are located in config_sample.py or config_docker.py.
we need to move them out of the sourcecode as a config json file, therefore, we don't have to rebuild the image when the config is different.

**Comment by juniwang** [comment]
config.json和config.py有什么本质区别？

**Comment by chensong2000** [comment]
我跟hypo讨论过，把配置文件放到代码之外，这样不用每次修改重新生成镜像。
config.py是代码，config.json更像是配置文件的形式。
没有本质区别，是形式上的区别。

**Comment by chensong2000** [comment]
keep it the way it is
