### ISSUE TITLE
开放黑客松推广系列专文

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-hackathon#748]
在 11/21   @@黑客松项目组例会里，我们提到了要对开放黑客松平台进一步宣传，收集一些过往案例，发几篇文章来推广。素材（图文）搜集及本文部分是否请 @pcwl 臧鹏 负责（ @tedliu1 Ted 可以协助润饰），媒体组 @cynbarby 这里可以协助编辑和发布。

**Comment by tedliu1** [comment]
开放黑客松云平台推广文（草稿）
https://shimo.im/docs/xKRyJjGG8khCJDJh

**Comment by tedliu1** [comment]
已完成黑客松活动编年史，可以准备移交给媒体组编辑。

**Comment by TechQuery** [comment]
https://mp.weixin.qq.com/s/C3IrNK-ikQrk6phkVEK1zw
