### ISSUE TITLE
docker-compose up失败

### ISSUE THREAD

**Issue by 99Kies** [kaiyuanshe/open-hackathon#767]
server 和 client启动失败

1.docker-compose up 启动失败 显示： 容器中 open-hackathon/deploy/hackathon-docker/docker-entrypoint-client.sh和/docker-entrypoint-server.sh 没有权限
> RUN chmod +x /opt/open-hackathon/deploy/hackathon-docker/docker-entrypoint-client.sh
> RUN chmod +x /opt/open-hackathon/deploy/hackathon-docker/docker-entrypoint-server.sh
2. 关于Dockerfile 建议将ADD更换为COPY

**Comment by chensong2000** [comment]
1，go to open-hackathon/deploy/hackathon-docker
2, sudo ./build.sh
3, sudo ./up.sh

try it again
