### ISSUE TITLE
处理更新Py3后的Bug

### ISSUE THREAD

**Issue by 99Kies** [kaiyuanshe/open-hackathon#787]
合并后，无法实现登入功能

**Comment by 99Kies** [comment]
- [ ] master 库中 需要将urllib2更换成urllib.request 或者考虑更换成requests
- [ ] 还有一些 dict类型的数据存在使用iteritems()的情况，需要更换成items()
- [ ] 合并产生的冲突内容还未删除
- [ ] 实现登入功能💪

--------
- [ ] bug list 
```bash
open-hackathon\open-hackathon-server\src\hackathon\__init__.py", line 102, in exception_handler
    return internal_server_error(error.message)
AttributeError: 'TypeError' object has no attribute 'message'
```

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/77237121-4dd7a780-6c00-11ea-985b-0b36c330708e.png)

**Comment by Coderhypo** [comment]
建议把每个 bug 单独一个 issue，在修复的时候可以将 pr 和 issue 跟踪做起来。

## Tips

修复之后，在 git commit message 可以加 issue 号，可以做到 pr 和 issue 自动关联，pr merge 之后 issue 自动关闭等操作。

举个例子，issue 787：错误处理会报 AttributeError

在修复之后，可以这样提交代码，

```
git commit -m "fix #787" 
```

然后在 issue 787 页可以看到新 pr，以及新 pr merge 之后 issue 787 就可以自动被 close。

**Comment by 99Kies** [comment]
> 建议把每个 bug 单独一个 issue，在修复的时候可以将 pr 和 issue 跟踪做起来。
> 
> ## Tips
> 修复之后，在 git commit message 可以加 issue 号，可以做到 pr 和 issue 自动关联，pr merge 之后 issue 自动关闭等操作。
> 
> 举个例子，issue 787：错误处理会报 AttributeError
> 
> 在修复之后，可以这样提交代码，
> 
> ```
> git commit -m "fix #787" 
> ```
> 
> 然后在 issue 787 页可以看到新 pr，以及新 pr merge 之后 issue 787 就可以自动被 close。

了解了，学习了👍
